### ISSUE TITLE
Zabbix Triggers List displays incorrectly on Grafana 5.0

### ISSUE THREAD

**Issue by helixzz** [alexanderzobnin/grafana-zabbix#540] opened 2018-03-07 03:26 UTC
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.0   | 3.0.4  | 3.8.1                 |

#### What did you do?
Insert a "Zabbix Triggers List" panel on grafana dashboard.

#### What was the expected result?
Displays as http://play.grafana-zabbix.org/dashboard/db/triggers examples.
As Attached #1.
![1](https://user-images.githubusercontent.com/12218889/37071997-474741a2-21fa-11e8-940f-020f13b02615.jpg)

#### What happened instead?
Displayed as four lines incorrectly. As attached #2.
![2](https://user-images.githubusercontent.com/12218889/37071999-477dcfd8-21fa-11e8-9610-215fdbb243df.jpg)

**Comment by agauthier51** [comment] 2018-03-07 08:07
Duplicate of #522

**Closed** 2018-03-15 18:22 UTC
Labels: duplicate
