### ISSUE TITLE
"Auto refresh" not working

### ISSUE THREAD

**Issue by tammytankian** [alexanderzobnin/grafana-zabbix#394] opened 2017-05-05 13:40 UTC
#### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [x] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using? 4.2.0
- What Zabbix version are you using? 3.2
- What zabbix plugin version are you using? 3.3.0
- What OS are you running grafana on? Debian 8.7

The automatic refresh is not really working, as showed in the images below. 
I thought that was a problem of Grafana, but @torkelo suggested that could be Zabbix. This used to work :/
The data showing on grafana just updates with F5 (Tested on Firefox and Google Chrome, same result)

**Before F5**
![before f5](https://cloud.githubusercontent.com/assets/27218076/25745732/bfde3f50-3176-11e7-914b-cafa8ac03f76.jpg)

**After F5**
![after f5](https://cloud.githubusercontent.com/assets/27218076/25745667/722c24b6-3176-11e7-9d85-8a519a45efe9.jpg)

**Network Request&Response 1**
![network1](https://cloud.githubusercontent.com/assets/27218076/25745682/7df0554c-3176-11e7-8c86-c34fce1d4b4d.PNG)

**Network Request&Response 2**
![network2](https://cloud.githubusercontent.com/assets/27218076/25745689/84419a50-3176-11e7-8949-16e7619d79fe.PNG)

Help?

**Comment by chancerollins** [comment] 2017-05-05 14:04
Just to chime in that I have noticed this exact issue as well.  I can confirm this in my environment. 

Grafana 4.2
Zabbix 3.2.4
Zabbix Plugin 3.3.0
Centos 7

**Comment by tammytankian** [comment] 2017-05-17 10:32
@alexanderzobnin I saw you labeled "Need more info"

How can I help? what do you need?

**Comment by alexanderzobnin** [comment] 2017-05-17 19:29
Is it happens after page load, or after some time? Is it works for other intervals (1m, 10s, etc)?

**Comment by tammytankian** [comment] 2017-05-17 19:43
> Is it happens after page load, or after some time?
You got me with this question, hehe What do you mean?

It just updates the data in the graphs and tables after a manual reload of the page. If I just leave the page there, never updates, as shown in the print screens.

> Is it works for other intervals (1m, 10s, etc)?

Nope. Intervals tested: everything after "1m". Already tried to change the cache configuration of the datasource, no help :/

**Comment by chancerollins** [comment] 2017-05-17 20:03
I just did some more testing and found that the updating on interval is actually working but it doesn't work in the background which is what I thought I remember happening in the past.  Most of my dashboards have an auto update 30 second interval.  If I switch tabs and come back an hour later it will update but it takes 30 seconds and doesn't refresh right away.  I have tested multiple dashboards to confirm this behavior.  

I don't know if this is the same issue or If I chimed in with a misdiagnosis.  Sorry for confusion.

**Comment by alexanderzobnin** [comment] 2017-05-19 14:09
Maybe there's a 4.2.0 bug? See here https://github.com/grafana/grafana/issues/8028
try to upgrade to 4.3 (currently in beta, will be released soon).

**Comment by chancerollins** [comment] 2017-05-19 14:17
That upstream bug looks like what I was seeing.  It looks like they pushed a change that will auto-refresh when the tab regains focus.  It's not critical so I'll probably wait for the production release of 4.3.  Good find Alexander.

**Comment by alexanderzobnin** [comment] 2017-05-19 14:19
Ok, sure.

**Comment by tammytankian** [comment] 2017-05-19 14:38
Most likely is this :/ I will wait for the release of 4.3...

Thank you for the help!

**Comment by alexanderzobnin** [comment] 2017-05-21 18:55
No problem. Let's sync it after upgrading.

**Comment by chancerollins** [comment] 2017-06-03 16:44
After installing 4.3.2 it appears fixed to me.  When you go back to the tab it quickly refreshes the dashboard.

**Closed** 2017-06-07 15:43 UTC
Labels: Need more info
