### ISSUE TITLE
Acknowledge with Zabbix 4.0.2 stopped working.

### ISSUE THREAD

**Issue by egnirra** [alexanderzobnin/grafana-zabbix#656] opened 2018-12-13 08:59 UTC
**Describe the bug**
When using the Acknowledge function in Alert list it does not work.
Nothing happens, no error messages.
It worked with Zabbix 3.4.12 (now we upgraded to 4.0.2)

**Expected behavior**
When using the acknowledge button i expect the text to show up and that the trigger is acknowledged in Zabbix. 

**Screenshots**
![image](https://user-images.githubusercontent.com/37709886/49926974-2a7e6280-febd-11e8-8c01-12167d99038a.png)
Console output
![image](https://user-images.githubusercontent.com/37709886/49926978-2ce0bc80-febd-11e8-932d-36bdee63426d.png)

**Network data**
N/A

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.4.1   | 4.0.2  | 3.9.1                 |

**Comment by alexanderzobnin** [comment] 2018-12-18 15:35
Duplicate of #629

**Closed by alexanderzobnin** 2018-12-18 15:35 UTC
