### ISSUE TITLE
The plugin is not working with Zabbix 6.2.0

### ISSUE THREAD

**Issue by ablecable** [alexanderzobnin/grafana-zabbix#1470] opened 2022-07-05 11:09 UTC
**Describe the bug**
It looks like grafana is not able to query hosts from the zabbix API (version 6.2)

**Expected behavior**
Query the hosts from zabbix

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.0.1   | 6.2.0  | 4.2.8             |

I think the API is changed:

[ZBXNEXT-2592](https://support.zabbix.com/browse/ZBXNEXT-2592) host.get: deprecated option selectGroups, new option selectHostGroups.

[ZBXNEXT-2592](https://support.zabbix.com/browse/ZBXNEXT-2592) hostgroup.get: deprecated options monitored_hosts, real_hosts, new options with_hosts, with_monitored_hosts.

**Comment by betaxab** [comment] 2022-07-05 12:37
please please update, @alexanderzobnin 

thanks

**Comment by eduardohaf** [comment] 2022-07-05 13:06
I have the same problem, @alexanderzobnin 

Thanks

**Comment by i-ky** [comment] 2022-07-05 13:15
Consider voting for [ZBX-19382](https://support.zabbix.com/browse/ZBX-19382).

**Comment by eduardohaf** [comment] 2022-07-05 14:00
Can anyone tell me which version of zabbix is compatible with the plugin at this time? 

@i-ky  Thanks

**Comment by tony-cp** [comment] 2022-07-05 15:39
> Can anyone tell me which version of zabbix is compatible with the plugin at this time?
> 
> @i-ky Thanks

It works with 6.0.x

I'm holding off upgrading to 6.2 because I rely on Grafana. Hopefully @alexanderzobnin has something in beta that can be released for 6.2 support.

**Comment by eduardohaf** [comment] 2022-07-05 21:00
@i-ky Thanks

**Comment by leleobhz** [comment] 2022-07-06 03:03
Hello!

https://github.com/Sam-H101/grafana-zabbix/tree/zabbix-6.2 started a fork to fix this issue and I also forked and started a work on https://github.com/leleobhz/grafana-zabbix/tree/zabbix-6.2 .

I'm facing some build errors on https://github.com/leleobhz/grafana-zabbix/runs/7207418213?check_suite_focus=true#step:5:338 and I'm also trying to continue a effort to support this version.

I'll keep working and hope someone comes with a PR before me :D

**Comment by xpowershellx** [comment] 2022-07-06 14:48
Same problem Grafana 9.0.1 and Zabbix 6.2 .

**Comment by Sam-H101** [comment] 2022-07-06 15:03
> Hello!
> 
> @Sam-H101 (https://github.com/Sam-H101/grafana-zabbix/tree/zabbix-6.2) has started a fork to fix this issue and I also forked and started a work on https://github.com/ZenithTecnologia/grafana-zabbix/tree/zabbix-6.2 .
> 
> I'm facing some build errors on https://github.com/leleobhz/grafana-zabbix/runs/7207418213?check_suite_focus=true#step:5:338 and I'm also trying to continue a effort to support this version.
> 
> I'll keep working and hope someone comes with a PR before me :D
> 
> Edit: Quote

Working on this issue in the mean time. I have something that atleast builds now, but will take a bit to get functional as I rarely do any typescript / go development. Not sure if my method of first checking the server version is a good one or not, so may not pan out.

**Comment by leleobhz** [comment] 2022-07-06 15:16
> > Hello!
> > @Sam-H101 (https://github.com/Sam-H101/grafana-zabbix/tree/zabbix-6.2) has started a fork to fix this issue and I also forked and started a work on https://github.com/ZenithTecnologia/grafana-zabbix/tree/zabbix-6.2 .
> > I'm facing some build errors on https://github.com/leleobhz/grafana-zabbix/runs/7207418213?check_suite_focus=true#step:5:338 and I'm also trying to continue a effort to support this version.
> > I'll keep working and hope someone comes with a PR before me :D
> > Edit: Quote
> 
> Working on this issue in the mean time. I have something that atleast builds now, but will take a bit to get functional as I rarely do any typescript / go development. Not sure if my method of first checking the server version is a good one or not, so may not pan out.

Hello @Sam-H101 

I did a successful compilation of you code at https://github.com/Sam-H101/grafana-zabbix/compare/zabbix-6.2...ZenithTecnologia:grafana-zabbix:zabbix-6.2 at this commit https://github.com/ZenithTecnologia/grafana-zabbix/commit/4c0ea97e8b066b70ab863fb9d1c8e722dd771e79 but Grafana still unable to fetch groups properly

I did some workarround to fix constant `params` scope issue too. If you dont mind, commit you latest changes to you branch too :)

**Comment by jchavezb-37** [comment] 2022-07-07 01:29
I have the same problem, @alexanderzobnin
:(

**Comment by isaqueprofeta** [comment] 2022-07-07 03:51
> Does anyone tried to downgrade zabbix from 6.2 to 6.0 ? DB schemas are compatible?

Downgrade in zabbix is a HUGE **NO-NO**

**Comment by iaroslav-vasiletc** [comment] 2022-07-07 07:57
> Does anyone tried to downgrade zabbix from 6.2 to 6.0 ? DB schemas are compatible?

Only if you have a backup of the database before you upgraded to 6.2, otherwise it just won't work, grafana won't show anything.
As a last resort, you can create a new 6.0 zabbix server from 0, export all hosts and templates from 6.2, and with a little editing of the export files you can import them into 6.0 without any problems.

**Comment by i-ky** [comment] 2022-07-07 08:07
> Does anyone tried to downgrade zabbix from 6.2 to 6.0 ?

Zabbix does not provide an option to downgrade the database. You have to backup before installing major Zabbix upgrades ("major" in case of Zabbix meaning "when major _or minor_ version number changes", so 6.0&rarr;6.2 included) to have a chance to go back.

> DB schemas are compatible?

Most likely not. I would strongly discourage trying to make Zabbix 6.0 work with 6.2 database (e.g. by hacking around `dbversion` manually), this will very likely [FUBAR](https://en.wiktionary.org/wiki/FUBAR) the database.

Maybe you can create a DB user with read-only permissions and make Zabbix 6.0 frontend (and consequently, API) use this user. You will need to hack it a bit [here](https://github.com/zabbix/zabbix/blob/931e073f3053f80810ff77a779d557f8af1d64e2/ui/include/defines.inc.php#L25):
```php
define('ZABBIX_DB_VERSION',		6000000);
```
Maybe this will work to some extent, but no guarantees. At least this approach will not damage your database.

**Comment by leleobhz** [comment] 2022-07-07 15:47
@isaqueprofeta A patch is in progress by community. If you really want to help, why not fork-and-help?

**Comment by leleobhz** [comment] 2022-07-07 16:33
@isaqueprofeta So please, if you can't patch it, please do not mess with devs that are trying to patch this issue. 

Also, you are always wellcome to fork and undo-XGH.

**Comment by leleobhz** [comment] 2022-07-07 20:38
For who want to check it:

I did a PR at https://github.com/Sam-H101/grafana-zabbix/pull/2 (@Sam-H101 repo's) and my current mindset is:

Function getGroups at line [140](https://github.com/ZenithTecnologia/grafana-zabbix/blob/zabbix-6.2/src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts#L140) fetches correctly data from Zabbix API

![image](https://user-images.githubusercontent.com/201189/177866967-1eff4121-fc25-49d4-9eab-e27a347333f5.png)

But when getHosts at line [175](https://github.com/ZenithTecnologia/grafana-zabbix/blob/zabbix-6.2/src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts#L175) got called, groupsid always get undefined and trigger conditional at line [183](https://github.com/ZenithTecnologia/grafana-zabbix/blob/zabbix-6.2/src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts#L183).

![image](https://user-images.githubusercontent.com/201189/177867081-ebb74438-7427-4f8d-903e-bed7816aafa8.png)

This condition send a undefined groupsid to Zabbix API and I dont think API expects this. I suspect some wrong treatment in the function [GetHosts at methods.go](https://github.com/ZenithTecnologia/grafana-zabbix/blob/zabbix-6.2/pkg/zabbix/methods.go#L227) but this function did not changed and apparently is not affected by 6.2 changes.

To simplify bug hunting, [this is the Changes on API from 6.0 to 6.2](https://www.zabbix.com/documentation/current/en/manual/api/changes_6.0_-_6.2).

I also created a new function on TS called `isZabbix62OrHigher()` to keep code minimally consistent with upstream.

**Comment by Sam-H101** [comment] 2022-07-07 21:26
I have tested with our main prod server aswell that is still 5.4.11 the code works with that, so I am likely missing something still, it may be part of the golang that the panel handles

**Comment by leleobhz** [comment] 2022-07-07 23:53
@Sam-H101 worked like a charm! If anyone needs a urgent artifact it can be grabbed at https://github.com/ZenithTecnologia/grafana-zabbix/actions/runs/2632963591

To use it, env `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-app,alexanderzobnin-zabbix-triggers-panel` must be set.

@Sam-H101 Do you want to finish a PR to @alexanderzobnin or want me to do it? Thank you so much for you effort together to have this issue fixed :)

**Comment by Sam-H101** [comment] 2022-07-07 23:57
Can you validate the metrics are still working without a database
connection? Or was that an existing issue?

And I can finish cleaning up and submit for a pr. It also has my other open
merge in it with the maintenance modes including tags instead of just
hosts.

**Comment by leleobhz** [comment] 2022-07-08 00:17
> Can you validate the metrics are still working without a database connection? Or was that an existing issue?

I can test in a next maintenance window here - probably in +- 20h~25h to go.

Its fair. I'll wait you PR. Ill keep the artifact to urgent matters until this PR gets merged here. Thanks!

**Comment by isaqueprofeta** [comment] 2022-07-08 00:56
> @isaqueprofeta So please, if you can't patch it, please do not mess with devs that are trying to patch this issue.
> 
> Also, you are always wellcome to fork and undo-XGH.

Whataheck man... I was talking about myself doing some XGH. Oh well. I just thinking about focus here (downgrade in zabbix isn't part of the issue, that's just my opinion ATM). Whatever, try to chill dude. I'll just erase my messages later ok?

**Comment by isaqueprofeta** [comment] 2022-07-08 00:57
> @Sam-H101 worked like a charm! If anyone needs a urgent artifact it can be grabbed at https://github.com/ZenithTecnologia/grafana-zabbix/actions/runs/2632963591
> 
> To use it, env `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-app,alexanderzobnin-zabbix-triggers-panel` must be set.
> 
> @Sam-H101 Do you want to finish a PR to @alexanderzobnin or want me to do it? Thank you so much for you effort together to have this issue fixed :)

I'll try to test it later when I'm at home. Thx for the easy zip for the ppl that rushed for the update on 6.2, if it's works I'll do a guide and post on the fóruns.

**Comment by ablecable** [comment] 2022-07-08 10:44
I tried these changes and now grafana is able to get the hosts but the items are not shown

**Comment by alexanderzobnin** [comment] 2022-07-08 11:01
It seems like a critical issue. I'll take a look asap.

**Comment by alexanderzobnin** [comment] 2022-07-08 11:58
The reason is that `hostgroup.get` does not return `groupid` property by default for some reason. Other methods work as expected, so probably, it a Zabbix API bug.

**Comment by Sam-H101** [comment] 2022-07-08 18:07
@ablecable latest build is working for me. For the items, you may have to clear out the host and readd it for it to load. or try refreshing the page once. 
I didn't update the PR I submitted with the latest build, but if you go back one, that build should also take care of the metrics issues it was having,

**Comment by xenadmin** [comment] 2022-07-09 12:56
> The reason is that `hostgroup.get` does not return `groupid` property by default for some reason. Other methods work as expected, so probably, it a Zabbix API bug.

Do you know, if there is already a ZBX-issue for the community to watch and vote for?

**Comment by alexanderzobnin** [comment] 2022-07-11 11:40
I talked to Zabbix devs, and they said this is the direction they want to go in future releases (only return objects ids if it was explicitly queried). So it won't be fixed on Zabbix side and I will push patch release soon.

**Closed** 2022-07-12 06:27 UTC
Labels: type: bug

**Comment by alexanderzobnin** [comment] 2022-07-12 06:44
Relase is pushed, waiting for team to approve publishing on grafana.com
https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v4.2.9

**Comment by vicentedeandrade** [comment] 2022-07-12 13:47
> Relase is pushed, waiting for team to approve publishing on grafana.com https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v4.2.9

@alexanderzobnin, thank you so much! Have a nice day!

**Comment by aha-sage** [comment] 2022-07-12 17:15
@alexanderzobnin seems that Alarms on Grafana (was working on last plugin release + Zabbix 6.0 + Grafana 9.0.2) got broken by Updating Zabbix to 6.2.

Panels are reading data just fine, but, when we try to setup alarms, no matter what I do, It only show: "no data"


Example:

In Panel (Graph got plotted):
![image](https://user-images.githubusercontent.com/93678419/178552327-d7e878aa-00bb-4532-b82d-ae54310420b0.png)

In Alert rule (Graph did not get plotted):
![image](https://user-images.githubusercontent.com/93678419/178552153-620db95f-60eb-4b05-98e1-1c23d97e9b8e.png)

Can you check if there is something just into alarm that needs to be fixed?

**Comment by alexanderzobnin** [comment] 2022-07-12 17:29
@aha-sage ok, I'll check it out.

**Comment by aha-sage** [comment] 2022-07-13 00:30
> @aha-sage ok, I'll check it out.

@alexanderzobnin it seems that I made a mistake while upgrading, because I was using the unsigned plugin mentioned before in this issue repport. 
When you said a new release was made, I updated by Grafana's webgui and I guess some files from the other build was kept there. So, I'm sorry for reopening this issue.

**Comment by pcamelio** [comment] 2022-07-13 07:29
Hi guys,
I upgrade the plugin, I just get the Problem dashboard working, Metrics are still unavailable while Group, Host, Item Tag and Item are working fine (select Group, then Host on this group etc .... but no data is get)

**Comment by MartinixH** [comment] 2022-07-13 07:36
@pcamelio did you restart grafana? I had to

**Comment by pcamelio** [comment] 2022-07-13 07:39
Thank you, @MartinixH 
You save my day :)

**Comment by alexourique** [comment] 2022-08-24 14:19
i have updated the plugin but the problem persists. Anyone with same problem?

**Comment by tikondrus** [comment] 2022-11-11 16:33
we have the same issue

Grafana 9.2.1
Zabbix 6.2.4
Grafana-Zabbix Plugin 4.2.10

After updating plugin the the lates 4.2.10 grafana dashboards is showing "no data"
Do we need to restart grafana after plugin installation?

**Comment by iny** [comment] 2023-05-16 09:00
The problem still persists on the versions written below, what can be done about the issue?


`FastCGI sent in stderr: "PHP message: PHP Deprecated:  Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1474PHP message: PHP Deprecated:  Parameter "/real_hosts" is deprecated.`

Zabbix 6.4.1
Grafana v9.4.7
Grafana-Zabbix Plugin 4.3.1

**Comment by leleobhz** [comment] 2023-05-17 17:55
> The problem still persists on the versions written below, what can be done about the issue? @alexanderzobnin
> 
> `FastCGI sent in stderr: "PHP message: PHP Deprecated: Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1474PHP message: PHP Deprecated: Parameter "/real_hosts" is deprecated.`
> 
> Zabbix 6.4.1 Grafana v9.4.7 Grafana-Zabbix Plugin 4.3.1

Hello @iny 

I suspect this is a new issue instead a regression about [hosthgroup.get](https://github.com/alexanderzobnin/grafana-zabbix/pull/1475). I suggest you to open a new issue.

**Comment by iny** [comment] 2023-05-17 19:25
Yes, I created an issue about it. @leleobhz 

#1633
