### ISSUE TITLE
Zabbix Problems Empty

### ISSUE THREAD

**Issue by ReiNoIkari** [alexanderzobnin/grafana-zabbix#1077] opened 2020-10-14 13:53 UTC
**Describe the bug**
When trying to display zabbix problems, the panel is empty showing "no problems found".
But when looking in the "data" tab of query inspector we can see there is data.

**Expected behavior**
Grafana zabbix problems showing all zabix problems.

**Screenshots**
Problem:
![zabbix problem](https://user-images.githubusercontent.com/23449208/95998581-4ba39780-0e35-11eb-84bd-8d2c13c007b1.png)

Data is here:
![data](https://user-images.githubusercontent.com/23449208/95997963-a5f02880-0e34-11eb-862f-f52cc21f42de.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.1   | 3.4.15  | 4.0.1                |

**Comment by arnydo** [comment] 2020-10-21 18:27
Same experience here.

**Comment by alexanderzobnin** [comment] 2020-11-03 09:22
Hi! I've found similar bug - when `Problem` field set to empty, then problems are not displayed. This bug caused by `null` value which is the filter set to. The workaround is using `/.*/` regex as a `Problem` filter. Could you confirm this workaround is fixing your issue? If yes, then you can use it and wait for the next release, where bug is fixed (6c20b07c69c7e5ef611aaa6b69f8eb678f77bb2e).

**Comment by SettonRA** [comment] 2020-11-11 18:35
Using /.*/ in the problems section worked for me.

**Comment by alexanderzobnin** [comment] 2020-11-13 09:09
Ok, so closing this - fix will be available in `4.0.2` release.

**Closed by alexanderzobnin** 2020-11-13 09:09 UTC
Labels: state: need more info

**Comment by eagolli** [comment] 2021-03-11 15:23
Hi,

I have exactly the same problem ReiNolkari has been reporting with this issue. So, the actual problems list remains empty although I can see quite a few data returned by the query. I understand the issue was supposed to be fixed in `4.0.2` but I seem to face it even now with latest plugin version `4.1.4`, Grafana 7.3.0 and Zabbix server version v3.4.1. I do not seem to work around this even by putting the `/.*/` regex in all the possible fields. I have actually tried many combinations of Grafana versions between 7.0.1 to latest 7.4.3 and plugin versions between 4.0.1 to the latest and the problem persists in all cases. Very weird. Could there be any explanation for this @alexanderzobnin?

Thanks,
Elton
