### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by yurtesen** [alexanderzobnin/grafana-zabbix#1124] opened 2020-12-28 13:30 UTC
**Describe the bug**
I updated to 4.1.0. The data alignment feature is causing `Cannot read property '1' of null` error in some graphs

**Expected behavior**
I expected graphs to work fine.

**Screenshots**
Without data alignment feature:
![image](https://user-images.githubusercontent.com/1926599/103217249-d8340100-4920-11eb-98fd-b5f7a1fce52f.png)
With the data alignment feature:
![image](https://user-images.githubusercontent.com/1926599/103217345-0addf980-4921-11eb-85af-07636a5f6f58.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.6   | 5.0.7  | 4.1.0                 |

**Comment by diegocanton** [comment] 2020-12-28 21:28
I see the same problem.

Grafana: 7.3.4
Zabbix: 4.2.8
Grafana-Zabbix Plugin: 4.1.0

The information below may perhaps help to identify the source of the problem.

I removed "Trends" parameters from the configuration, as I found in another issue that incorrect values could cause this. That did not solve it.

I found that when using "/.*/" in application the error does not appear, but neither does the data. One of my DASH had the value of "application" filled with the value used in Zabbix and presented data in 3 of the 9 panels. All panels have "application" defined.

I returned to Grafana-Zabbix Plugin: 4.0.2 and the problem is fixed

**Comment by MGlants** [comment] 2020-12-29 00:32
Same here

**Comment by WillemWever** [comment] 2020-12-29 08:59
We are having the same issue.

Grafana: 7.3.6
Zabbix: 5.0.3
Grafana-Zabbix Plugin: 4.1.0

We returned to Grafana-Zabbix Plugin: 4.0.2 and the dashboards are working as expected.

**Comment by estevaocm14** [comment] 2020-12-29 13:43
We had the same problem. 

Grafana: 7.3.6
Zabbix: 5.2.3
Grafana-Zabbix Plugin: 4.1.0

As soon as we downgraded to version 4.0.2, everything was back to normal.

**Comment by yurtesen** [comment] 2020-12-29 22:14
I have a question for people who downgraded it. I simply disabled it in data source settings by enabling "Disable data alignment" knob. Didn't this fix your problem?

**Comment by WillemWever** [comment] 2020-12-30 09:33
> I have a question for people who downgraded it. I simply disabled it in data source settings by enabling "Disable data alignment" knob. Didn't this fix your problem?

Yes it does, but I cannot find a central place to change this for all the items on our dashboards.

**Comment by yurtesen** [comment] 2020-12-30 09:44
@WillemWever isn't the `Configuration -> Data Sources -> Zabbix` the central place?
![image](https://user-images.githubusercontent.com/1926599/103343204-39301600-4a94-11eb-98db-ca24216fcc32.png)
![image](https://user-images.githubusercontent.com/1926599/103343213-41885100-4a94-11eb-8ff2-047a47221b83.png)
Anyway, perhaps not that important detail, I was just wondering why people were downgrading the plugin because it seemed like that knob turned off the problem globally for me.

**Comment by alexanderzobnin** [comment] 2020-12-30 10:24
Duplicates #1123
Workaround described in the issue.

**Comment by alexanderzobnin** [comment] 2020-12-30 10:28
As @yurtesen mentioned, you can disable data alignment for all queries in the data source config. However, this option required for proper stacked graphs in the next Grafana release. So make sure you enable it back after updating plugin (fix is on the way).

**Comment by alexanderzobnin** [comment] 2020-12-30 11:54
Fixed in the latest release (4.1.1). So you can upgrade plugin to fix this issue.

**Comment by WillemWever** [comment] 2020-12-30 12:14
> Fixed in the latest release (4.1.1). So you can upgrade plugin to fix this issue.

Upgraded succesfull to 4.1.1. No problems at all.

Thanks!

**Comment by diegocanton** [comment] 2020-12-30 18:03
4.1.1 - solved

**Comment by yurtesen** [comment] 2020-12-31 11:47
The graphs are working, but I am not sure if the feature is working. I am not able to achieve graphs like the author mentioned at:
https://github.com/alexanderzobnin/grafana-zabbix/issues/1109#issuecomment-749543471
Mine look like :(
![image](https://user-images.githubusercontent.com/1926599/103409267-a7e1a200-4b6e-11eb-8046-e234785b52c2.png)

**Closed** 2021-01-20 12:49 UTC
Labels: type: duplicate
