### ISSUE TITLE
a.replaceTemplateVars is not a function

### ISSUE THREAD

**Issue by msjohansen** [alexanderzobnin/grafana-zabbix#895] opened 2020-02-20 08:04 UTC
**Describe the bug**
When trying to view a local snapshot containing "Zabbix Problems" panel i'm presented with the error "a.replaceTemplateVars is not a function" and an empty panel list.

Panel data error: TypeError: a.replaceTemplateVars is not a function
    at eval (triggers_panel_ctrl.js:266)
    at async Promise.all (:3000/dashboard/snapshot/index 0)

**Expected behavior**
I would expect a current list of known issues/problems from zabbix

**Screenshots**
[image](https://i.imgur.com/PGPDmfr.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.6.1   | 4.4.5  | 3.10.5                 |

**Comment by alexanderzobnin** [comment] 2020-03-23 15:28
Hi! Could you try latest 3.11 version. I can't replicate this on my test instance.

**Comment by IHeilig** [comment] 2020-03-27 17:43
I have the same issue when trying to share a dashboard with Grafana snapshots. Steps to reproduce:
- create a dashboard with Zabbix problems plugin
- create snapshot URL
- open the URL

Result:
![image](https://user-images.githubusercontent.com/46581629/77783667-ef785200-7061-11ea-87b9-2937a9332c05.png)

Info: Grafana 6.7.1
Plugin: 3.11.0

**Comment by alexanderzobnin** [comment] 2020-04-10 11:05
Could you post a panel JSON (for failed panel only)?

**Comment by msjohansen** [comment] 2020-04-15 15:38
This is the panel JSON when viewing from the snapshot
```json
{
  "datasource": null,
  "ackEventColor": "rgb(56, 219, 156)",
  "ageField": true,
  "customLastChangeFormat": false,
  "descriptionAtNewLine": false,
  "descriptionField": true,
  "fontSize": "100%",
  "gridPos": {
    "h": 17,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "highlightBackground": false,
  "highlightNewEvents": true,
  "highlightNewerThan": "1h",
  "hostField": true,
  "hostGroups": false,
  "hostProxy": false,
  "hostTechNameField": false,
  "hostsInMaintenance": false,
  "id": 2,
  "lastChangeFormat": "",
  "layout": "table",
  "limit": 100,
  "links": [],
  "markAckEvents": false,
  "okEventColor": "rgb(56, 189, 113)",
  "options": {},
  "pageSize": 100,
  "problemTimeline": true,
  "resizedColumns": [],
  "schemaVersion": 7,
  "severityField": true,
  "showEvents": {
    "text": "Problems",
    "value": 1
  },
  "showTags": false,
  "showTriggers": "all triggers",
  "sortTriggersBy": {
    "text": "severity",
    "value": "priority"
  },
  "statusField": true,
  "statusIcon": true,
  "targets": [
    {
      "refId": "A",
      "group": {
        "filter": ""
      },
      "host": {
        "filter": ""
      },
      "application": {
        "filter": ""
      },
      "trigger": {
        "filter": ""
      },
      "tags": {
        "filter": ""
      },
      "proxy": {
        "filter": ""
      }
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Known issues",
  "transparent": true,
  "triggerSeverity": [
    {
      "color": "rgb(108, 108, 108)",
      "priority": 0,
      "severity": "Not classified",
      "show": true
    },
    {
      "color": "rgb(120, 158, 183)",
      "priority": 1,
      "severity": "Information",
      "show": true
    },
    {
      "color": "rgb(175, 180, 36)",
      "priority": 2,
      "severity": "Warning",
      "show": true
    },
    {
      "color": "rgb(255, 137, 30)",
      "priority": 3,
      "severity": "Average",
      "show": true
    },
    {
      "color": "rgb(255, 101, 72)",
      "priority": 4,
      "severity": "High",
      "show": true
    },
    {
      "color": "rgb(215, 0, 0)",
      "priority": 5,
      "severity": "Disaster",
      "show": true
    }
  ],
  "type": "alexanderzobnin-zabbix-triggers-panel"
}
```

**Comment by alexanderzobnin** [comment] 2021-03-09 11:36
@msjohansen since problems panel architecture was changed (now it only shows the data got from data source), I think this issue is not happening anymore. I'm closing this, but let me know if it still persists in the latest version.

**Closed by alexanderzobnin** 2021-03-09 11:36 UTC
Labels: state: need more info, type: bug
