### ISSUE TITLE
Zabbix 6 Service SLA

### ISSUE THREAD

**Issue by OlivierGALEOTE** [alexanderzobnin/grafana-zabbix#1398] opened 2022-02-22 14:00 UTC
Hello,

After migrating from Zabbix to version 6, the "IT Services" query mode no longer works.
We have the error message: "Method not found. Incorrect method "service.getsla".
"
Grafana is in version 8.4.1 and the zabbix plugin is in 4.2.5.

Do you know the problem?

Thank you

**Comment by Sam-H101** [comment] 2022-02-22 21:40
it looks like zabbix 6.0 removed the service.getsla method and instead built out its own sla endpoint.

sla.get and sla.getsli

https://www.zabbix.com/documentation/current/en/manual/api/reference/sla/get

There will need to be a code update for this plugin before this will work again. Best solution if this is critical data would be to downgrade your zabbix back to 5.4.x.

**Comment by i-ky** [comment] 2022-02-22 22:03
There was a similar #1188 when Zabbix 5.4 was released. Please vote for [ZBX-19382](https://support.zabbix.com/browse/ZBX-19382) and spread the word about it to make sure the issue is addressed by Zabbix team. Downgrading Zabbix is a pain.

**Comment by OlivierGALEOTE** [comment] 2022-02-24 14:00
Hello,

Thank you for your answers.
I went directly to the database in the service table.

**Closed** 2022-02-24 14:00 UTC

**Comment by mbuyukkarakas** [comment] 2022-03-14 06:21
Same problem. Needs fixing.
