### ISSUE TITLE
Warnings about closed stream

### ISSUE THREAD

**Issue by fansari** [alexanderzobnin/grafana-zabbix#1157] opened 2021-02-12 13:36 UTC
**Describe the bug**
When Grafana is receiving data via the Zabbix plugin I notice a lot of messages like this:
t=2021-02-12T13:28:35+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"

**Expected behavior**
No such warnings/errors.

**Software versions**
I use the Grafana Docker image.

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.4.1   | 5.2.4  | 4.1.2                 |

**Comment by alexanderzobnin** [comment] 2021-02-15 14:20
That's probably related to the backend-plugins-sdk, since logger is not a plugin. But I'll take a look, maybe this caused by plugin somehow.

**Comment by cuspat96** [comment] 2021-02-19 06:22
Hi Alexander,
I have the same issue. Let me know if you need more logs.

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.4.2 | 5.2.4 | 4.1.2

**Comment by TrickUK** [comment] 2021-02-19 14:38
My install is also exhibiting this behaviour:

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.4.2 | 4.0.28 | 4.1.2

**Comment by wangxin688** [comment] 2021-02-24 02:31
has same issue too

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.4.2 | 5.2.0 | 4.1.2

**Comment by e-chernis** [comment] 2021-03-01 13:28
Same issue 

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.4.3 | 5.2.5 | 4.1.2

**Comment by JSuenram** [comment] 2021-03-03 15:39
Can confirm some Plugins show n/a-data or nothing at all.
Grafana 7.4.3 Zabbix 4.0.29 Grafana-Zabbix Plugin 4.1.2

**Comment by e-chernis** [comment] 2021-03-03 16:01
> Can confirm some Plugins show n/a-data or nothing at all.
> Grafana 7.4.3 Zabbix 4.0.29 Grafana-Zabbix Plugin 4.1.2

Data is sent correctly to the widget, you have to update your display(fields) or transforms on Grafana and keep it working

**Comment by JSuenram** [comment] 2021-03-03 16:13
> > Can confirm some Plugins show n/a-data or nothing at all.
> > Grafana 7.4.3 Zabbix 4.0.29 Grafana-Zabbix Plugin 4.1.2
> 
> Data is sent correctly to the widget, you have to update your display(fields) or transforms on Grafana for keep it working

Downgrade Grafana-Zabbix Plugin 4.0.1 resolved issue.... https://github.com/alexanderzobnin/grafana-zabbix/issues/1161

**Comment by alexanderzobnin** [comment] 2021-03-05 08:29
Unfortunately, I cannot reproduce issue so far. Could you give me more details/logs when it may happen?

**Comment by fcollado** [comment] 2021-03-05 08:46
Hi,

In our case (Grafana 7.4.3, Zabbix 5.0.9, Grafana-Zabbix Plugin 4.1.2) is very easy to reproduce it. 

Any dashboards with data from Zabbix had small gaps and produce a random amount or these type of logs:

> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
> t=2021-03-05T08:37:04+0000 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"

It happens with version 4.1.1 and 4.1.2. 4.0.2 works ok, no gaps and no logs. Do you need another kind of logs, captures or data?

**Comment by alexanderzobnin** [comment] 2021-03-05 09:11
Ok, I see the same on my demo instance after upgrading plugin/grafana to latest versions. Investigating.

**Comment by alexanderzobnin** [comment] 2021-03-05 09:21
Warning caused by this lines, added in last grafana release: 
https://github.com/grafana/grafana/blob/fb58c0638335af13ea4cc6e91749ae70327cf0ab/pkg/plugins/backendplugin/manager.go#L288-L290

I don't think it's a problem, just a warning. Looking for the root cause, not sure why stream is closed.

**Comment by alexanderzobnin** [comment] 2021-03-05 09:38
Ok, it looks like message related to plugin sdk, not a plugin itself. So closing this since it's not an error.

**Closed by alexanderzobnin** 2021-03-05 09:38 UTC
Labels: state: need more info
