### ISSUE TITLE
Can't acknowledge resolved problem

### ISSUE THREAD

**Issue by diogogarbinsouza** [alexanderzobnin/grafana-zabbix#942] opened 2020-05-12 21:52 UTC
**Permission Error when attempt to send acknowledge in a resolved problem**
When I try to send an acknowledge to resolved problem the trigger panel show me a permission error msg:

"zabbix apI Error: Application error. No permissions to referred object or it does not exist!"

there is any troubleshooting to do ?

**Expected behavior**
Send Ackowledge to a resolved problem

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.6.2   | 4.4.1  | 3.10.5            |

**Comment by alexanderzobnin** [comment] 2020-05-13 12:57
Yes, confirmed. The most likely reason is a hardcoded API request flags - I use `acknowledge event` and `add message`. Looks like `acknowledge event` is not allowed for resolved problems. So I need to add options to the acknowledge dialog, like in recent Zabbix versions:

![Screenshot from 2020-05-13 15-55-14](https://user-images.githubusercontent.com/4932851/81815251-70b47700-9532-11ea-9059-3bc699f9b274.png)

**Comment by diogogarbinsouza** [comment] 2020-05-13 13:42
Thank you so much for your reply, in this case there is nothing that I can do, correct ? Sad cause I've been work on a monitoring project that must force an human action to any problem even if it was resolved. 

Once again thank you, if you have any suggestion please contact me

**Comment by alexanderzobnin** [comment] 2020-05-14 05:42
@diogogarbinsouza yes, that's a bug in the plugin, so just wait for the next version, it should be fixed.

**Closed** 2020-05-18 16:46 UTC
Labels: comp: Problems panel, type: bug

**Comment by alexanderzobnin** [comment] 2020-05-18 16:48
Acknowledge dialog was updadted. Now it's possible to select ask actions:

![Screenshot from 2020-05-18 19-48-19](https://user-images.githubusercontent.com/4932851/82238821-8f56ab80-9940-11ea-9085-2d277e25cd63.png)

**Comment by diogogarbinsouza** [comment] 2020-05-18 17:46
thank you so much

**Comment by diogogarbinsouza** [comment] 2020-05-18 18:02
Sorry but I am begginer with github, I just need to copy these files and change in my local server ?

**Comment by diogogarbinsouza** [comment] 2020-05-19 12:30
I reinstalled the API and even can't reproduce the window above, can you help me ?

**Comment by alexanderzobnin** [comment] 2020-05-20 13:57
This update wasn't released yet. So just wait few days for the plugin relase (3.12) and then update with grafana-cli.

**Comment by diogogarbinsouza** [comment] 2020-05-20 21:33
so sorry, thank you

**Comment by Vitaliy155** [comment] 2021-09-10 14:11
@alexanderzobnin I use version 4.2.2 but still have error.
I checked this bug on your demo zabbix and  got error as well 
https://play.grafana-zabbix.org/d/000000024/problems?orgId=2 

![Screenshot 2021-09-10 170939](https://user-images.githubusercontent.com/90462334/132867039-420e04b3-6063-455b-9638-4f6517276725.png)

**Comment by alexanderzobnin** [comment] 2021-09-10 14:31
It's because I use read-only user for API connection. So it does not have permissions to close problem.
