### ISSUE TITLE
Fetch error: 404 Not Found Instantiating after upgrading to grafana 5.1.3 windows

### ISSUE THREAD

**Issue by ravend05** [alexanderzobnin/grafana-zabbix#584] opened 2018-06-07 01:15 UTC
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [x ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.3   |3.2.6 | 3.6.1                |

#### What did you do?
I upgraded grafana from V v4.4.3 to 5.1.3 
I followed the instruction from the website : 

If you downloaded the binary tar package you can just download and extract a new package and overwrite all your existing files. But this might overwrite your config changes. We recommend you place your config changes in a file named <grafana_install_dir>/conf/custom.ini as this will make upgrades easier without risking losing your config changes.

Restarted the service and get error message on the new dashboard 

" Plugin Error

XHR error: (404 Not Found) loading 
https://grafana.xxxx.xxx:8080/public/tether-drop Instantiating 
https://grafana.xxxx.xxx:8080/public/tether-drop Loading 
https://grafana.xxxx.xxx:8080/public/plugins/alexanderzobnin-zabbix-
app/panel-triggers/ack-tooltip.directive.js Loading plugins/alexanderzobnin-zabbix-
app/panel-triggers/module

Could someone please help , thanks a lot

**Comment by krptg** [comment] 2018-06-13 13:32
Duplicate of #574

**Comment by krptg** [comment] 2018-06-13 13:32
Solution in #574

**Closed** 2018-06-19 07:03 UTC
Labels: duplicate
