### ISSUE TITLE
Broken formating in Triggers Panel (Grafana 5)

### ISSUE THREAD

**Issue by MosinAnton** [alexanderzobnin/grafana-zabbix#522] opened 2018-02-06 06:59 UTC
### I'm submitting a ...
- [*] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.0-beta1   | 3.4.4  | 3.8.1               |

#### What happened instead?
Trigger's panel in Grafana 5 looks like this

![image](https://user-images.githubusercontent.com/15945872/35845520-a07861f2-0b34-11e8-9672-6f5393ac6db0.png)

**Comment by agauthier51** [comment] 2018-02-06 09:47
Confirmed using both Zabbix 3.4.6 & Zabbix 2.4.8 (Grafana-Zabbix Plugin 3.8.1).

**Comment by Atem18** [comment] 2018-03-01 11:20
Same problem with the new released final 5.0

**Comment by Usever** [comment] 2018-03-02 20:28
Confirmed!

**Comment by bmathieu33** [comment] 2018-03-06 10:49
Alert list markup [has changed in 5.0](https://github.com/grafana/grafana/commit/5d5de230259b83393eb8200e58791ec98e21f4fb#diff-1a2c760de3d78d259f1385d284769bc7)

Here is the current template: https://github.com/grafana/grafana/blob/07fa2f17222fb81b83c96601367d4b8e967be886/public/app/plugins/panel/alertlist/module.html

**Comment by helixzz** [comment] 2018-03-07 03:27
Same problem. https://github.com/alexanderzobnin/grafana-zabbix/issues/540

**Comment by agauthier51** [comment] 2018-03-13 11:18
@bmathieu33 proposed modification works for me (zabbix 2.4.8 & 3.4.7, grafana 5.0

**Comment by winderickxeli** [comment] 2018-03-15 10:02
@agauthier , @bmathieu33 I've tried altering the three files but my grafana still looks like  
![35845520-a07861f2-0b34-11e8-9672-6f5393ac6db0](https://user-images.githubusercontent.com/19908773/37456724-5801ebea-2840-11e8-821c-c66acaeea692.png)

Are there other changes that need to occur in the settings? Is a reboot of Grafana sufficient?

**Comment by alexanderzobnin** [comment] 2018-03-15 14:58
Fixed, will be released soon.

**Closed by alexanderzobnin** 2018-03-15 14:58 UTC
Labels: Triggers panel, bug, in progress
