### ISSUE TITLE
Reg Ex with Item Tag

### ISSUE THREAD

**Issue by omega949** [alexanderzobnin/grafana-zabbix#1275] opened 2021-08-25 15:50 UTC
**Describe the bug**
Unable to use regex on "Item tag", please see screen shot.. When i leave that area blank i can use the item and do do regex but not in the new tag section.

**Expected behavior**
Ability to use standard regex on item tag

**Screenshots**
![image](https://user-images.githubusercontent.com/40457866/130822648-7a674193-ad82-4614-b1da-77f134a6468e.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.3   | 5.4-1  | 4.2.1                |

**Comment by alexanderzobnin** [comment] 2021-09-10 13:49
I think it's the same root cause as for #1283, because the variable is added as a regex. So closing this, fix will be in the upcoming release.

**Closed by alexanderzobnin** 2021-09-10 13:49 UTC
