### ISSUE TITLE
Zabbix plugin crashes constanly under certain conditions

### ISSUE THREAD

**Issue by Oberon520** [alexanderzobnin/grafana-zabbix#1296] opened 2021-09-09 15:30 UTC
**Describe the bug**
Zabbix plugin crashes in some graphs with 100% probability

**Expected behavior**
Zabbix plugin to work.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/49863474/132715522-b2ced372-d68a-4c2f-8ade-4884acd85ecf.png)

**Network data**
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "refId": "A",
          "resultFormat": "time_series",
          "itemTag": {
            "filter": ""
          },
          "queryType": "0",
          "group": {
            "filter": "Kafka"
          },
          "host": {
            "filter": "/.*/"
          },
          "application": {
            "filter": ""
          },
          "item": {
            "filter": "Kafka prd.sub.create: Messages in per second"
          },
          "functions": [],
          "triggers": {
            "count": true,
            "minSeverity": 3,
            "acknowledged": 2
          },
          "trigger": {
            "filter": ""
          },
          "tags": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "options": {
            "showDisabledItems": false,
            "skipEmptyValues": false,
            "disableDataAlignment": false,
            "useZabbixValueMapping": false
          },
          "table": {
            "skipEmptyValues": false
          },
          "datasource": "zabbix",
          "datasourceId": 2,
          "intervalMs": 2000,
          "maxDataPoints": 1699
        }
      ],
      "range": {
        "from": "2021-09-09T14:26:06.826Z",
        "to": "2021-09-09T15:26:06.826Z",
        "raw": {
          "from": "now-1h",
          "to": "now"
        }
      },
      "from": "1631197566826",
      "to": "1631201166826"
    },
    "hideFromInspector": false
  },
  "response": {
    "message": "Metric request error"
  }
}

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.3  | 5.4.3  | 4.2.2                 |

Log data:
t=2021-09-09T18:16:23+0300 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac62fa]" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg= logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="goroutine 44 [running]:" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/timeseries.AlignSeriesIntervals(0xc00055e100, 0x3, 0x4, 0x11c1d00, 0x2ca4d540, 0xed8cc1c45)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/timeseries/align.go:90 +0x5a" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/datasource.(*ZabbixDatasourceInstance).applyDataProcessing(0xc00048a7b0, 0xd63e38, 0xc0003e44e0, 0xc0003fe000, 0xc00055e100, 0x3, 0x4, 0x3, 0x4, 0xc001e4e000, ...)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/datasource/zabbix.go:129 +0x705" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/datasource.(*ZabbixDatasourceInstance).queryNumericDataForItems(0xc00048a7b0, 0xd63e38, 0xc0003e44e0, 0xc0003fe000, 0xc00055f280, 0x3, 0x4, 0x0, 0x0, 0x0, ...)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/datasource/zabbix.go:105 +0x265" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/datasource.(*ZabbixDatasourceInstance).queryNumericItems(0xc00048a7b0, 0xd63e38, 0xc0003e44e0, 0xc0003fe000, 0x2, 0x2, 0x2ca4d540, 0xed8cc0e35, 0x11c1d00)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/datasource/zabbix.go:59 +0x150" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/datasource.(*ZabbixDatasource).QueryData(0xc00031a620, 0xd63e38, 0xc0003e44e0, 0xc000388be0, 0xb71580, 0xd53e40, 0xbc1a00)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/datasource/datasource.go:121 +0x74b" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/backend.(*dataSDKAdapter).QueryData(0xc000325870, 0xd63e38, 0xc0003e44e0, 0xc0003888c0, 0xb71580, 0x0, 0xd53e40)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/backend/data_adapter.go:21 +0x63" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/backend/grpcplugin.(*dataGRPCServer).QueryData(0xc000325ae0, 0xd63e38, 0xc0003e44e0, 0xc0003888c0, 0xc000325ae0, 0x7f80a83cf880, 0xc00007ef00)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/backend/grpcplugin/grpc_data.go:47 +0x51" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/genproto/pluginv2._Data_QueryData_Handler.func1(0xd63e38, 0xc0003e44e0, 0xc02800, 0xc0003888c0, 0x18, 0xc000388b90, 0x7f80a85dfd40, 0x20)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/genproto/pluginv2/backend_grpc.pb.go:191 +0x89" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0xd63e38, 0xc0003e44e0, 0xc02800, 0xc0003888c0, 0xc00031a8c0, 0xc000306900, 0xa6889a, 0xbf2760, 0xc00031a8e0, 0xc00031a8c0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xb0" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xd63e38, 0xc0003e44e0, 0xc02800, 0xc0003888c0, 0xc00005e800, 0x0, 0xc0004a1b30, 0x40fdb8)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0xd63e38, 0xc0003e44e0, 0xc02800, 0xc0003888c0, 0xc00031a8c0, 0xc000306900, 0xc0003f7ba0, 0x49dd86, 0xc09ec0, 0xc0003e44e0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xd7" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/genproto/pluginv2._Data_QueryData_Handler(0xb71580, 0xc000325ae0, 0xd63e38, 0xc0003e44e0, 0xc0003a91a0, 0xc000317a10, 0xd63e38, 0xc0003e44e0, 0xc00036d400, 0x48a)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/genproto/pluginv2/backend_grpc.pb.go:193 +0x150" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003296c0, 0xd6adb8, 0xc000408180, 0xc000333560, 0xc0003e4240, 0x11a9dc0, 0x0, 0x0, 0x0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1217 +0x52b" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="google.golang.org/grpc.(*Server).handleStream(0xc0003296c0, 0xd6adb8, 0xc000408180, 0xc000333560, 0x0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1540 +0xd0c" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00042e020, 0xc0003296c0, 0xd6adb8, 0xc000408180, 0xc000333560)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:878 +0xab" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="created by google.golang.org/grpc.(*Server).serveStreams.func1" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:876 +0x1fd" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="plugin process exited" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64 pid=2817770 error="exit status 2"
t=2021-09-09T18:16:23+0300 lvl=eror msg="Metric request error" logger=context userId=13 orgId=1 uname= error="failed to query data: Failed to query data: rpc error: code = Unavailable desc = error reading from server: EOF" remote_addr=
t=2021-09-09T18:16:23+0300 lvl=dbug msg="token needs rotation" logger=auth tokenId=1373 authTokenSeen=true rotatedAt=2021-09-09T18:06:02+0300
t=2021-09-09T18:16:23+0300 lvl=dbug msg="auth token rotated" logger=auth affected=1 auth_token_id=1373 userId=13
t=2021-09-09T18:16:23+0300 lvl=eror msg="Request Completed" logger=context userId=13 orgId=1 uname= method=POST path=/api/ds/query status=500 remote_addr=192.168.10.218 time_ms=2262 size=34 referer="
t=2021-09-09T18:16:23+0300 lvl=dbug msg="Restarting plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="starting plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64 args=[/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64]
t=2021-09-09T18:16:23+0300 lvl=dbug msg="plugin started" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64 pid=2818451
t=2021-09-09T18:16:23+0300 lvl=dbug msg="waiting for RPC address" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
t=2021-09-09T18:16:23+0300 lvl=info msg=Profiler logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource enabled=false
t=2021-09-09T18:16:23+0300 lvl=dbug msg="Could not read environment variable" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource EXTRA_VALUE_AT_END=GFX_ZABBIX_DATA_PATH
t=2021-09-09T18:16:23+0300 lvl=dbug msg="Starting Zabbix datasource" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-09T18:16:23+0300 lvl=dbug msg="Serving plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource plugins="[data diagnostics resource]"
t=2021-09-09T18:16:23+0300 lvl=dbug msg="plugin address" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource address=/tmp/plugin952448475 network=unix
t=2021-09-09T18:16:23+0300 lvl=dbug msg="using plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource version=2
t=2021-09-09T18:16:23+0300 lvl=dbug msg="Plugin restarted" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource

**Comment by nullemotion** [comment] 2021-09-10 11:27
Same issue. 
The problem is related to using regex in fields "Host" or "Item" in query. 
There is a group of hosts named XXX-PR-001, XXX-PR-002... When regex looks like full hostname (e.g. /XXX-PR-001/) - all works fine. No regex - all fine. 
When regex intend more than one result (e.g. /.*/ or /XXX-PR/) sometimes it cause plugin crush, sometimes it just a message: "Metric request error" in query inspector.
Grafana 8.1.3, plugin 4.2.2, zabbix 5.4.4.

**Comment by alexanderzobnin** [comment] 2021-09-10 11:34
Hi! This is a duplicate of #1279

**Closed by alexanderzobnin** 2021-09-10 11:34 UTC
