### ISSUE TITLE
can't query influx: this.influxDS._seriesQuery(...).then is not a function

### ISSUE THREAD

**Issue by ramon-roca** [alexanderzobnin/grafana-zabbix#1255] opened 2021-08-05 19:39 UTC
Just installed Zabbix 5.0 TLS, grafana 8.0.6, zabbix plugin 4.1.5, Direct DB to influx (1.8.7) with effluence-0.1 on ubuntu 20.04 TLS.
History is being exported to Influx DB, but  getting error on all queries to metrics:
```
 "this.influxDS._seriesQuery(...).then is not a function" 
```

querying directly from grafana to influx data source, works.

**Comment by i-ky** [comment] 2021-08-05 21:52
This may be a duplicate of #1221.

**Comment by ramon-roca** [comment] 2021-08-06 06:06
#1221 suggests downgrade to grafana 7.5 as a workaround. I did but problem persists. Disabling Direct DB works, but we're planning intensive graphing on large number of items, and long history.

May I help providing more trace?

**Comment by alexanderzobnin** [comment] 2021-08-11 08:42
@ramon-roca can you test is against plugin version 4.2.1 and confirm that problem exists/solved?

**Comment by ramon-roca** [comment] 2021-08-11 15:56
> @ramon-roca can you test is against plugin version 4.2.1 and confirm that problem exists/solve

thanks, @alexanderzobnin 
upgraded to 4.2.1 but no luck, still reproducing with a simple query:
![image](https://user-images.githubusercontent.com/16072373/129062461-f3aaf704-37c6-40eb-a4d1-df89119ab3f2.png)

**Comment by julienleboeuf** [comment] 2021-08-19 15:17
I confirm, I have the same problem since months ago, and was stuck with grafana 7.3
Still the same with grafana 8.1.1 and plugin 4.2.1 (with InfluQL & InfluxDB 1.8.4)

**Comment by julienleboeuf** [comment] 2021-11-02 08:28
Still no news ?
I guess I'll have to discard directdb+influxdb and switch to postgresql/timescaledb

**Comment by dimsua** [comment] 2022-05-19 09:44
still not work, innodb direct connection deprecated?

**Comment by pyite** [comment] 2022-08-30 17:15
I am having the same problem on 7.x.  IIRC, I tried 8.x and also had no luck.

If I build a query in InfluxDB and use the Influx plugin directly, it is like 1000x faster than the MySQL direct DB query... so I am highly motivated to make this work.

Unfortunately, the query inspector icon just spins so it's difficult to see exactly what the Zabbix module is trying to do.

Any idea what to try next?  A few months ago I tried building the module myself to debug and traced the code deep into one of the libraries but didn't have time to finish debugging.  It wasn't a very fun process due to the security changes and code signing requirements.

**Comment by alexanderzobnin** [comment] 2022-08-31 12:40
Hi! Here's a linux build with a fix. Please, try to test it out and confirm that issue is fixed.
[alexanderzobnin-zabbix-app-4.3.0-pre.zip](https://github.com/alexanderzobnin/grafana-zabbix/files/9461563/alexanderzobnin-zabbix-app-4.3.0-pre.zip)

**Closed** 2022-09-01 05:59 UTC
Labels: type: bug, comp: DB connector

**Comment by pyite** [comment] 2022-09-01 15:20
This fix works for me, thank you!!
